### ISSUE TITLE
Can't make it work. Async error on node 9.11

### ISSUE THREAD

**Issue by roberpreston** [nikersify/alfred-polyglot#3]
I can't get it to work.

Node version:
```
$ node -v
$ v9.11.1
```
Debug output:
```
Starting debug for 'Google Translate'

[2018-06-07 12:27:58][ERROR: input.scriptfilter] Code 1: /Users/…/Config files/Alfred Workflow Configs/Alfred.alfredpreferences/workflows/user.workflow.AFBC9248-2F9C-45BA-BA11-1A8823D84C47/index.js:5
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by nikersify** [comment]
I think your alfred is somehow using an older version of node. Would you mind putting `console.log(process.version)` above the line that's throwing the error for you and sharing the debug output?

**Comment by roberpreston** [comment]
Sorry, I didn't notice your answer. You're right I solved it. 
Thank you!
