### ISSUE TITLE
Unknown error in <anonymous>

### ISSUE THREAD

**Issue by KennethSundqvist** [nikersify/alfred-polyglot#4]
Just installed `alfred-polyglot@1.2.0` via NPM and I'm getting this error:

```
Error
    at /Users/eom/.nvm/versions/node/v8.12.0/lib/node_modules/alfred-polyglot/node_modules/google-translate-api/index.js:105:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

The full log from the Alfred debugger:

```
[2018-10-14 20:56:11][input.scriptfilter] Queuing argument ''
[2018-10-14 20:56:11][input.scriptfilter] Script with argument '' finished
[2018-10-14 20:56:11][input.scriptfilter] {
	"items": [
		{
			"title": "Translate '...'"
		}
	]
}
[2018-10-14 20:56:11][input.scriptfilter] Queuing argument 'h'
[2018-10-14 20:56:11][input.scriptfilter] Queuing argument 'he'
[2018-10-14 20:56:11][input.scriptfilter] Queuing argument 'hej'
[2018-10-14 20:56:12][input.scriptfilter] Script with argument 'hej' finished
[2018-10-14 20:56:12][input.scriptfilter] {
	"items": [
		{
			"title": "Error: ",
			"subtitle": "Activate this item to try again. | ⌘L to see the stack trace",
			"autocomplete": "",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			},
			"valid": false,
			"text": {
				"largetype": "Error\n    at /Users/eom/.nvm/versions/node/v8.12.0/lib/node_modules/alfred-polyglot/node_modules/google-translate-api/index.js:105:17\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)",
				"copy": "Error\n    at /Users/eom/.nvm/versions/node/v8.12.0/lib/node_modules/alfred-polyglot/node_modules/google-translate-api/index.js:105:17\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
			}
		}
	]
}
```

**Comment by AlexMartinFR** [comment]
I'm having the same issue, also installed this workflow via npm today.

`Error\n    at /usr/local/lib/node_modules/alfred-polyglot/node_modules/google-translate-api/index.js:105:17\n    at process._tickCallback (internal/process/next_tick.js:68:7) `

**Comment by KennethSundqvist** [comment]
Sweet! Installing the tkk-fix branch fixes issue for me.

**Comment by AlexMartinFR** [comment]
I confirm it's working now, thanks for this great workflow!
